import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

type WriteAppFilesOptions = {
  projectDir: string;
  tgzPath: string;
};

export const writeAppFiles = async ({ projectDir, tgzPath }: WriteAppFilesOptions) => {
  const convexDir = join(projectDir, 'convex');
  const libDir = join(projectDir, 'lib');
  const repoRoot = resolve(fileURLToPath(new URL('../..', import.meta.url)));
  await mkdir(convexDir, { recursive: true });
  await mkdir(libDir, { recursive: true });

  const r2Source = await readFile(join(repoRoot, 'example', 'lib', 'r2.ts'), 'utf8');
  const stepsSource = await readFile(
    join(repoRoot, 'example', 'lib', 'transloadit-steps.ts'),
    'utf8',
  );
  await writeFile(join(libDir, 'r2.ts'), r2Source, 'utf8');
  await writeFile(join(libDir, 'transloadit-steps.ts'), stepsSource, 'utf8');

  await writeFile(
    join(projectDir, 'package.json'),
    JSON.stringify(
      {
        name: 'transloadit-convex-qa',
        private: true,
        type: 'module',
        dependencies: {
          '@convex-dev/auth': '^0.0.90',
          '@transloadit/convex': `file:${tgzPath}`,
          '@transloadit/zod': '^4.1.9',
          convex: '^1.31.5',
          zod: '^4.3.5',
        },
      },
      null,
      2,
    ),
    'utf8',
  );

  await writeFile(
    join(convexDir, 'convex.config.ts'),
    [
      'import transloadit from "@transloadit/convex/convex.config";',
      'import { defineApp } from "convex/server";',
      '',
      'const app = defineApp();',
      'app.use(transloadit);',
      '',
      'export default app;',
      '',
    ].join('\n'),
    'utf8',
  );

  await writeFile(
    join(convexDir, 'schema.ts'),
    [
      'import { defineSchema, defineTable } from "convex/server";',
      'import { authTables } from "@convex-dev/auth/server";',
      'import { v } from "convex/values";',
      '',
      'export default defineSchema({',
      '  ...authTables,',
      '  uploadLimits: defineTable({',
      '    userId: v.string(),',
      '    windowStart: v.number(),',
      '    count: v.number(),',
      '    lastUploadAt: v.number(),',
      '  }).index("by_user", ["userId"]),',
      '});',
      '',
    ].join('\n'),
    'utf8',
  );

  await writeFile(
    join(convexDir, 'auth.ts'),
    [
      'import { convexAuth } from "@convex-dev/auth/server";',
      'import { Anonymous } from "@convex-dev/auth/providers/Anonymous";',
      '',
      'const ensureConvexSiteUrl = () => {',
      '  if (process.env.CONVEX_SITE_URL) return;',
      '  const convexUrl = process.env.CONVEX_URL;',
      '  if (!convexUrl) return;',
      '  if (!convexUrl.includes(".convex.cloud")) return;',
      '  process.env.CONVEX_SITE_URL = convexUrl.replace(".convex.cloud", ".convex.site");',
      '};',
      '',
      'ensureConvexSiteUrl();',
      '',
      'export const { auth, signIn, signOut, store, isAuthenticated } = convexAuth({',
      '  providers: [Anonymous],',
      '});',
      '',
    ].join('\n'),
    'utf8',
  );

  await writeFile(
    join(convexDir, 'auth.config.ts'),
    [
      'const siteUrl =',
      '  process.env.CONVEX_SITE_URL ??',
      '  (process.env.CONVEX_URL?.includes(".convex.cloud")',
      '    ? process.env.CONVEX_URL.replace(".convex.cloud", ".convex.site")',
      '    : process.env.CONVEX_URL);',
      '',
      'if (!siteUrl) {',
      '  throw new Error("Missing CONVEX_SITE_URL or CONVEX_URL for auth.config.ts");',
      '}',
      '',
      'export default {',
      '  providers: [',
      '    {',
      '      domain: siteUrl,',
      '      applicationID: "convex",',
      '    },',
      '  ],',
      '};',
      '',
    ].join('\n'),
    'utf8',
  );

  await writeFile(
    join(convexDir, 'transloadit.ts'),
    [
      'import {',
      '  vAssemblyResponse,',
      '  vAssemblyResultResponse,',
      '  vCreateAssemblyArgs,',
      '} from "@transloadit/convex";',
      'import { actionGeneric, componentsGeneric, mutationGeneric, queryGeneric } from "convex/server";',
      'import { v } from "convex/values";',
      '',
      'const components = componentsGeneric();',
      '',
      'const readConfig = () => {',
      '  const authKey = process.env.TRANSLOADIT_KEY;',
      '  if (!authKey) {',
      '    throw new Error("Missing TRANSLOADIT_KEY environment variable");',
      '  }',
      '  const authSecret = process.env.TRANSLOADIT_SECRET;',
      '  if (!authSecret) {',
      '    throw new Error("Missing TRANSLOADIT_SECRET environment variable");',
      '  }',
      '  return { authKey, authSecret };',
      '};',
      '',
      'export const createAssembly = actionGeneric({',
      '  args: vCreateAssemblyArgs,',
      '  returns: v.object({',
      '    assemblyId: v.string(),',
      '    data: v.any(),',
      '  }),',
      '  handler: async (ctx, args) => {',
      '    return ctx.runAction(components.transloadit.lib.createAssembly, {',
      '      ...args,',
      '      config: readConfig(),',
      '    });',
      '  },',
      '});',
      '',
      'export const handleWebhook = actionGeneric({',
      '  args: {',
      '    payload: v.any(),',
      '    rawBody: v.optional(v.string()),',
      '    signature: v.optional(v.string()),',
      '    verifySignature: v.optional(v.boolean()),',
      '  },',
      '  returns: v.object({',
      '    assemblyId: v.string(),',
      '    resultCount: v.number(),',
      '  }),',
      '  handler: async (ctx, args) => {',
      '    const { authSecret } = readConfig();',
      '    return ctx.runAction(components.transloadit.lib.handleWebhook, {',
      '      ...args,',
      '      config: { authSecret },',
      '    });',
      '  },',
      '});',
      '',
      'export const queueWebhook = actionGeneric({',
      '  args: {',
      '    payload: v.any(),',
      '    rawBody: v.optional(v.string()),',
      '    signature: v.optional(v.string()),',
      '    verifySignature: v.optional(v.boolean()),',
      '  },',
      '  returns: v.object({',
      '    assemblyId: v.string(),',
      '    queued: v.boolean(),',
      '  }),',
      '  handler: async (ctx, args) => {',
      '    const { authSecret } = readConfig();',
      '    return ctx.runAction(components.transloadit.lib.queueWebhook, {',
      '      ...args,',
      '      config: { authSecret },',
      '    });',
      '  },',
      '});',
      '',
      'export const refreshAssembly = actionGeneric({',
      '  args: { assemblyId: v.string() },',
      '  returns: v.object({',
      '    assemblyId: v.string(),',
      '    resultCount: v.number(),',
      '    ok: v.optional(v.string()),',
      '    status: v.optional(v.string()),',
      '  }),',
      '  handler: async (ctx, args) => {',
      '    return ctx.runAction(components.transloadit.lib.refreshAssembly, {',
      '      ...args,',
      '      config: readConfig(),',
      '    });',
      '  },',
      '});',
      '',
      'export const getAssemblyStatus = queryGeneric({',
      '  args: { assemblyId: v.string() },',
      '  returns: v.union(vAssemblyResponse, v.null()),',
      '  handler: async (ctx, args) => {',
      '    return ctx.runQuery(components.transloadit.lib.getAssemblyStatus, args);',
      '  },',
      '});',
      '',
      'export const listAssemblies = queryGeneric({',
      '  args: {',
      '    status: v.optional(v.string()),',
      '    userId: v.optional(v.string()),',
      '    limit: v.optional(v.number()),',
      '  },',
      '  returns: v.array(vAssemblyResponse),',
      '  handler: async (ctx, args) => {',
      '    return ctx.runQuery(components.transloadit.lib.listAssemblies, args);',
      '  },',
      '});',
      '',
      'export const listResults = queryGeneric({',
      '  args: {',
      '    assemblyId: v.string(),',
      '    stepName: v.optional(v.string()),',
      '    limit: v.optional(v.number()),',
      '  },',
      '  returns: v.array(vAssemblyResultResponse),',
      '  handler: async (ctx, args) => {',
      '    return ctx.runQuery(components.transloadit.lib.listResults, args);',
      '  },',
      '});',
      '',
      'export const listAlbumResults = queryGeneric({',
      '  args: {',
      '    album: v.string(),',
      '    limit: v.optional(v.number()),',
      '  },',
      '  returns: v.array(vAssemblyResultResponse),',
      '  handler: async (ctx, args) => {',
      '    return ctx.runQuery(components.transloadit.lib.listAlbumResults, args);',
      '  },',
      '});',
      '',
      'export const storeAssemblyMetadata = mutationGeneric({',
      '  args: {',
      '    assemblyId: v.string(),',
      '    userId: v.optional(v.string()),',
      '    fields: v.optional(v.record(v.string(), v.any())),',
      '  },',
      '  returns: v.union(vAssemblyResponse, v.null()),',
      '  handler: async (ctx, args) => {',
      '    return ctx.runMutation(components.transloadit.lib.storeAssemblyMetadata, args);',
      '  },',
      '});',
      '',
    ].join('\n'),
    'utf8',
  );

  await writeFile(
    join(convexDir, 'wedding.ts'),
    [
      'import { vAssemblyOptions } from "@transloadit/convex";',
      'import { v } from "convex/values";',
      'import { action, internalMutation } from "./_generated/server";',
      'import { components, internal } from "./_generated/api";',
      'import { buildWeddingSteps } from "../lib/transloadit-steps";',
      '',
      'const MAX_UPLOADS_PER_HOUR = 6;',
      'const WINDOW_MS = 60 * 60 * 1000;',
      '',
      'const requireEnv = (name: string) => {',
      '  const value = process.env[name];',
      '  if (!value) {',
      '    throw new Error("Missing " + name + " environment variable");',
      '  }',
      '  return value;',
      '};',
      '',
      'export const checkUploadLimit = internalMutation({',
      '  args: { userId: v.string() },',
      '  returns: v.null(),',
      '  handler: async (ctx, args) => {',
      '    const now = Date.now();',
      '    const existing = await ctx.db',
      '      .query("uploadLimits")',
      '      .withIndex("by_user", (q) => q.eq("userId", args.userId))',
      '      .first();',
      '    if (!existing) {',
      '      await ctx.db.insert("uploadLimits", {',
      '        userId: args.userId,',
      '        windowStart: now,',
      '        count: 1,',
      '        lastUploadAt: now,',
      '      });',
      '      return null;',
      '    }',
      '    if (now - existing.windowStart > WINDOW_MS) {',
      '      await ctx.db.patch(existing._id, {',
      '        windowStart: now,',
      '        count: 1,',
      '        lastUploadAt: now,',
      '      });',
      '      return null;',
      '    }',
      '    if (existing.count >= MAX_UPLOADS_PER_HOUR) {',
      '      throw new Error("Upload limit reached. Try again later.");',
      '    }',
      '    await ctx.db.patch(existing._id, {',
      '      count: existing.count + 1,',
      '      lastUploadAt: now,',
      '    });',
      '    return null;',
      '  },',
      '});',
      '',
      'export const createWeddingAssemblyOptions = action({',
      '  args: {',
      '    fileCount: v.number(),',
      '    guestName: v.optional(v.string()),',
      '    uploadCode: v.optional(v.string()),',
      '  },',
      '  returns: v.object({',
      '    assemblyOptions: vAssemblyOptions,',
      '    params: v.any(),',
      '  }),',
      '  handler: async (ctx, args) => {',
      '    const identity = await ctx.auth.getUserIdentity();',
      '    if (!identity) {',
      '      throw new Error("Authentication required.");',
      '    }',
      '    await ctx.runMutation(internal.wedding.checkUploadLimit, { userId: identity.subject });',
      '',
      '    const requiredCode = process.env.WEDDING_UPLOAD_CODE;',
      '    if (requiredCode) {',
      '      const provided = args.uploadCode?.trim();',
      '      if (!provided || provided !== requiredCode) {',
      '        throw new Error("Upload code required.");',
      '      }',
      '    }',
      '',
      '    const steps = buildWeddingSteps();',
      '    const notifyUrl = requireEnv("TRANSLOADIT_NOTIFY_URL");',
      '    const fileCount = Math.max(1, args.fileCount);',
      '    const assemblyArgs = {',
      '      steps,',
      '      notifyUrl,',
      '      numExpectedUploadFiles: fileCount,',
      '      fields: {',
      '        guestName: args.guestName ?? "Guest",',
      '        album: "wedding-gallery",',
      '        fileCount,',
      '        userId: identity.subject,',
      '      },',
      '      userId: identity.subject,',
      '    };',
      '    const assemblyOptions = await ctx.runAction(',
      '      components.transloadit.lib.createAssemblyOptions,',
      '      {',
      '        ...assemblyArgs,',
      '        config: {',
      '          authKey: requireEnv("TRANSLOADIT_KEY"),',
      '          authSecret: requireEnv("TRANSLOADIT_SECRET"),',
      '        },',
      '      },',
      '    );',
      '    const parsedParams = safeParseParams(assemblyOptions.params);',
      '    const params = redactSecrets(parsedParams ?? assemblyArgs);',
      '    return { assemblyOptions, params };',
      '  },',
      '});',
      '',
      'const safeParseParams = (value: string) => {',
      '  try {',
      '    return JSON.parse(value);',
      '  } catch (error) {',
      '    console.warn("Failed to parse Transloadit params", error);',
      '    return null;',
      '  }',
      '};',
      '',
      'const secretKeys = new Set([',
      '  "secret",',
      '  "key",',
      '  "credentials",',
      '  "authSecret",',
      '  "authKey",',
      ']);',
      '',
      'const redactSecrets = (value: unknown): unknown => {',
      '  if (Array.isArray(value)) {',
      '    return value.map((item) => redactSecrets(item));',
      '  }',
      '  if (value && typeof value === "object") {',
      '    const entries = Object.entries(value).map(([key, val]) => {',
      '      if (secretKeys.has(key)) {',
      '        return [key, "***"];',
      '      }',
      '      return [key, redactSecrets(val)];',
      '    });',
      '    return Object.fromEntries(entries);',
      '  }',
      '  return value;',
      '};',
      '',
    ].join('\n'),
    'utf8',
  );

  await writeFile(
    join(convexDir, 'http.ts'),
    [
      'import { handleWebhookRequest } from "@transloadit/convex";',
      'import { httpRouter, httpActionGeneric } from "convex/server";',
      'import { api } from "./_generated/api";',
      '',
      'const http = httpRouter();',
      'const httpAction = httpActionGeneric;',
      '',
      'const requireEnv = (name: string) => {',
      '  const value = process.env[name];',
      '  if (!value) {',
      '    throw new Error("Missing " + name);',
      '  }',
      '  return value;',
      '};',
      '',
      'http.route({',
      '  path: "/.well-known/openid-configuration",',
      '  method: "GET",',
      '  handler: httpAction(async () => {',
      '    const siteUrl = requireEnv("CONVEX_SITE_URL");',
      '    const jwksUrl = new URL(".well-known/jwks.json", siteUrl).toString();',
      '    const authorizeUrl = new URL("oauth/authorize", siteUrl).toString();',
      '    return new Response(',
      '      JSON.stringify({',
      '        issuer: siteUrl,',
      '        jwks_uri: jwksUrl,',
      '        authorization_endpoint: authorizeUrl,',
      '      }),',
      '      {',
      '        status: 200,',
      '        headers: {',
      '          "Content-Type": "application/json",',
      '          "Cache-Control":',
      '            "public, max-age=15, stale-while-revalidate=15, stale-if-error=86400",',
      '        },',
      '      },',
      '    );',
      '  }),',
      '});',
      '',
      'http.route({',
      '  path: "/.well-known/jwks.json",',
      '  method: "GET",',
      '  handler: httpAction(async () => {',
      '    return new Response(requireEnv("JWKS"), {',
      '      status: 200,',
      '      headers: {',
      '        "Content-Type": "application/json",',
      '        "Cache-Control":',
      '          "public, max-age=15, stale-while-revalidate=15, stale-if-error=86400",',
      '      },',
      '    });',
      '  }),',
      '});',
      '',
      'http.route({',
      '  path: "/transloadit/webhook",',
      '  method: "POST",',
      '  handler: httpAction(async (ctx, request) => {',
      '    return handleWebhookRequest(request, {',
      '      mode: "queue",',
      '      runAction: (args) => ctx.runAction(api.transloadit.queueWebhook, args),',
      '    });',
      '  }),',
      '});',
      '',
      'export default http;',
      '',
    ].join('\n'),
    'utf8',
  );
};
