import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

type WriteAppFilesOptions = {
  projectDir: string;
  tgzPath: string;
};

export const writeAppFiles = async ({
  projectDir,
  tgzPath,
}: WriteAppFilesOptions) => {
  const convexDir = join(projectDir, "convex");
  await mkdir(convexDir, { recursive: true });

  await writeFile(
    join(projectDir, "package.json"),
    JSON.stringify(
      {
        name: "transloadit-convex-qa",
        private: true,
        type: "module",
        dependencies: {
          "@convex-dev/auth": "^0.0.90",
          "@transloadit/convex": `file:${tgzPath}`,
          convex: "^1.31.5",
        },
      },
      null,
      2,
    ),
    "utf8",
  );

  await writeFile(
    join(convexDir, "convex.config.ts"),
    [
      'import transloadit from "@transloadit/convex/convex.config";',
      'import { defineApp } from "convex/server";',
      "",
      "const app = defineApp();",
      "app.use(transloadit);",
      "",
      "export default app;",
      "",
    ].join("\n"),
    "utf8",
  );

  await writeFile(
    join(convexDir, "schema.ts"),
    [
      'import { defineSchema, defineTable } from "convex/server";',
      'import { authTables } from "@convex-dev/auth/server";',
      'import { v } from "convex/values";',
      "",
      "export default defineSchema({",
      "  ...authTables,",
      "  uploadLimits: defineTable({",
      "    userId: v.string(),",
      "    windowStart: v.number(),",
      "    count: v.number(),",
      "    lastUploadAt: v.number(),",
      '  }).index("by_user", ["userId"]),',
      "});",
      "",
    ].join("\n"),
    "utf8",
  );

  await writeFile(
    join(convexDir, "auth.ts"),
    [
      'import { convexAuth } from "@convex-dev/auth/server";',
      'import { Anonymous } from "@convex-dev/auth/providers/Anonymous";',
      "",
      "export const { auth, signIn, signOut, store, isAuthenticated } = convexAuth({",
      "  providers: [Anonymous],",
      "});",
      "",
    ].join("\n"),
    "utf8",
  );

  await writeFile(
    join(convexDir, "http.ts"),
    [
      'import { parseTransloaditWebhook } from "@transloadit/convex";',
      'import { httpRouter } from "convex/server";',
      'import { auth } from "./auth";',
      'import { api } from "./_generated/api";',
      'import { httpAction } from "./_generated/server";',
      "",
      "const http = httpRouter();",
      "",
      "auth.addHttpRoutes(http);",
      "",
      "http.route({",
      '  path: "/transloadit/webhook",',
      '  method: "POST",',
      "  handler: httpAction(async (ctx, request) => {",
      "    const { payload, rawBody, signature } =",
      "      await parseTransloaditWebhook(request);",
      "",
      "    await ctx.runAction(api.transloadit.queueWebhook, {",
      "      payload,",
      "      rawBody,",
      "      signature,",
      "    });",
      "",
      "    return new Response(null, { status: 202 });",
      "  }),",
      "});",
      "",
      "export default http;",
      "",
    ].join("\n"),
    "utf8",
  );

  await writeFile(
    join(convexDir, "transloadit.ts"),
    [
      "import {",
      "  vAssemblyResponse,",
      "  vAssemblyResultResponse,",
      "  vCreateAssemblyArgs,",
      '} from "@transloadit/convex";',
      'import { actionGeneric, componentsGeneric, mutationGeneric, queryGeneric } from "convex/server";',
      'import { v } from "convex/values";',
      "",
      "const components = componentsGeneric();",
      "",
      "const readConfig = () => {",
      "  const authKey = process.env.TRANSLOADIT_KEY;",
      "  if (!authKey) {",
      '    throw new Error("Missing TRANSLOADIT_KEY environment variable");',
      "  }",
      "  const authSecret = process.env.TRANSLOADIT_SECRET;",
      "  if (!authSecret) {",
      '    throw new Error("Missing TRANSLOADIT_SECRET environment variable");',
      "  }",
      "  return { authKey, authSecret };",
      "};",
      "",
      "export const createAssembly = actionGeneric({",
      "  args: vCreateAssemblyArgs,",
      "  returns: v.object({",
      "    assemblyId: v.string(),",
      "    data: v.any(),",
      "  }),",
      "  handler: async (ctx, args) => {",
      "    return ctx.runAction(components.transloadit.lib.createAssembly, {",
      "      ...args,",
      "      config: readConfig(),",
      "    });",
      "  },",
      "});",
      "",
      "export const handleWebhook = actionGeneric({",
      "  args: {",
      "    payload: v.any(),",
      "    rawBody: v.optional(v.string()),",
      "    signature: v.optional(v.string()),",
      "    verifySignature: v.optional(v.boolean()),",
      "  },",
      "  returns: v.object({",
      "    assemblyId: v.string(),",
      "    resultCount: v.number(),",
      "  }),",
      "  handler: async (ctx, args) => {",
      "    const { authSecret } = readConfig();",
      "    return ctx.runAction(components.transloadit.lib.handleWebhook, {",
      "      ...args,",
      "      config: { authSecret },",
      "    });",
      "  },",
      "});",
      "",
      "export const queueWebhook = actionGeneric({",
      "  args: {",
      "    payload: v.any(),",
      "    rawBody: v.optional(v.string()),",
      "    signature: v.optional(v.string()),",
      "    verifySignature: v.optional(v.boolean()),",
      "  },",
      "  returns: v.object({",
      "    assemblyId: v.string(),",
      "    queued: v.boolean(),",
      "  }),",
      "  handler: async (ctx, args) => {",
      "    const { authSecret } = readConfig();",
      "    return ctx.runAction(components.transloadit.lib.queueWebhook, {",
      "      ...args,",
      "      config: { authSecret },",
      "    });",
      "  },",
      "});",
      "",
      "export const refreshAssembly = actionGeneric({",
      "  args: { assemblyId: v.string() },",
      "  returns: v.object({",
      "    assemblyId: v.string(),",
      "    resultCount: v.number(),",
      "    ok: v.optional(v.string()),",
      "    status: v.optional(v.string()),",
      "  }),",
      "  handler: async (ctx, args) => {",
      "    return ctx.runAction(components.transloadit.lib.refreshAssembly, {",
      "      ...args,",
      "      config: readConfig(),",
      "    });",
      "  },",
      "});",
      "",
      "export const getAssemblyStatus = queryGeneric({",
      "  args: { assemblyId: v.string() },",
      "  returns: v.union(vAssemblyResponse, v.null()),",
      "  handler: async (ctx, args) => {",
      "    return ctx.runQuery(components.transloadit.lib.getAssemblyStatus, args);",
      "  },",
      "});",
      "",
      "export const listAssemblies = queryGeneric({",
      "  args: {",
      "    status: v.optional(v.string()),",
      "    userId: v.optional(v.string()),",
      "    limit: v.optional(v.number()),",
      "  },",
      "  returns: v.array(vAssemblyResponse),",
      "  handler: async (ctx, args) => {",
      "    return ctx.runQuery(components.transloadit.lib.listAssemblies, args);",
      "  },",
      "});",
      "",
      "export const listResults = queryGeneric({",
      "  args: {",
      "    assemblyId: v.string(),",
      "    stepName: v.optional(v.string()),",
      "    limit: v.optional(v.number()),",
      "  },",
      "  returns: v.array(vAssemblyResultResponse),",
      "  handler: async (ctx, args) => {",
      "    return ctx.runQuery(components.transloadit.lib.listResults, args);",
      "  },",
      "});",
      "",
      "export const storeAssemblyMetadata = mutationGeneric({",
      "  args: {",
      "    assemblyId: v.string(),",
      "    userId: v.optional(v.string()),",
      "    fields: v.optional(v.record(v.string(), v.any())),",
      "  },",
      "  returns: v.union(vAssemblyResponse, v.null()),",
      "  handler: async (ctx, args) => {",
      "    return ctx.runMutation(components.transloadit.lib.storeAssemblyMetadata, args);",
      "  },",
      "});",
      "",
    ].join("\n"),
    "utf8",
  );

  await writeFile(
    join(convexDir, "wedding.ts"),
    [
      'import { action, internalMutation } from "./_generated/server";',
      'import { v } from "convex/values";',
      'import { components } from "./_generated/api";',
      "",
      "const MAX_UPLOADS_PER_HOUR = 6;",
      "const WINDOW_MS = 60 * 60 * 1000;",
      "",
      "const requireEnv = (name: string) => {",
      "  const value = process.env[name];",
      "  if (!value) {",
      '    throw new Error("Missing " + name + " environment variable");',
      "  }",
      "  return value;",
      "};",
      "",
      "const buildWeddingSteps = () => {",
      "  const credentials = process.env.TRANSLOADIT_R2_CREDENTIALS;",
      "  const bucket = process.env.R2_BUCKET;",
      "  const accessKeyId = process.env.R2_ACCESS_KEY_ID;",
      "  const secretAccessKey = process.env.R2_SECRET_ACCESS_KEY;",
      "  const accountId = process.env.R2_ACCOUNT_ID;",
      "  const host =",
      "    process.env.R2_HOST ??",
      '    (accountId ? accountId + ".r2.cloudflarestorage.com" : undefined);',
      "  const urlPrefix = process.env.R2_PUBLIC_URL;",
      "",
      "  if (!credentials && (!bucket || !accessKeyId || !secretAccessKey)) {",
      '    throw new Error("Missing R2 credentials. Set TRANSLOADIT_R2_CREDENTIALS or R2_BUCKET/R2_ACCESS_KEY_ID/R2_SECRET_ACCESS_KEY.");',
      "  }",
      "  if (!credentials && !host) {",
      '    throw new Error("Missing R2 host. Set R2_HOST or R2_ACCOUNT_ID.");',
      "  }",
      "",
      "  const storeStep = {",
      '    robot: "/cloudflare/store",',
      "    result: true,",
      '    path: "wedding/" + "$" + "{fields.album}" + "/" + "$" + "{unique_prefix}" + "/" + "$" + "{file.url_name}",',
      "  } as Record<string, unknown>;",
      "",
      "  if (credentials) {",
      "    storeStep.credentials = credentials;",
      "  } else {",
      "    storeStep.bucket = bucket;",
      "    storeStep.key = accessKeyId;",
      "    storeStep.secret = secretAccessKey;",
      "    storeStep.host = host;",
      "  }",
      "  if (urlPrefix) {",
      "    storeStep.url_prefix = urlPrefix;",
      "  }",
      "",
      "  return {",
      '    ":original": { robot: "/upload/handle" },',
      "    images_filtered: {",
      '      use: ":original",',
      '      robot: "/file/filter",',
      '      accepts: [["$" + "{file.mime}", "regex", "^image"]],',
      "      error_on_decline: false,",
      "    },",
      "    videos_filtered: {",
      '      use: ":original",',
      '      robot: "/file/filter",',
      '      accepts: [["$" + "{file.mime}", "regex", "^video"]],',
      "      error_on_decline: false,",
      "    },",
      "    images_resized: {",
      '      use: "images_filtered",',
      '      robot: "/image/resize",',
      "      width: 1600,",
      "      height: 1600,",
      '      resize_strategy: "fit",',
      "    },",
      "    videos_encoded: {",
      '      use: "videos_filtered",',
      '      robot: "/video/encode",',
      '      preset: "ipad-high",',
      "    },",
      '    images_output: { ...storeStep, use: "images_resized" },',
      '    videos_output: { ...storeStep, use: "videos_encoded" },',
      "  };",
      "};",
      "",
      "const checkUploadLimit = internalMutation({",
      "  args: { userId: v.string() },",
      "  returns: v.null(),",
      "  handler: async (ctx, args) => {",
      "    const now = Date.now();",
      "    const existing = await ctx.db",
      '      .query("uploadLimits")',
      '      .withIndex("by_user", (q) => q.eq("userId", args.userId))',
      "      .first();",
      "    if (!existing) {",
      '      await ctx.db.insert("uploadLimits", {',
      "        userId: args.userId,",
      "        windowStart: now,",
      "        count: 1,",
      "        lastUploadAt: now,",
      "      });",
      "      return null;",
      "    }",
      "    if (now - existing.windowStart > WINDOW_MS) {",
      "      await ctx.db.patch(existing._id, {",
      "        windowStart: now,",
      "        count: 1,",
      "        lastUploadAt: now,",
      "      });",
      "      return null;",
      "    }",
      "    if (existing.count >= MAX_UPLOADS_PER_HOUR) {",
      '      throw new Error("Upload limit reached. Try again later.");',
      "    }",
      "    await ctx.db.patch(existing._id, {",
      "      count: existing.count + 1,",
      "      lastUploadAt: now,",
      "    });",
      "    return null;",
      "  },",
      "});",
      "",
      "export const createWeddingAssembly = action({",
      "  args: {",
      "    fileCount: v.number(),",
      "    guestName: v.optional(v.string()),",
      "    uploadCode: v.optional(v.string()),",
      "  },",
      "  returns: v.object({",
      "    assemblyId: v.string(),",
      "    data: v.any(),",
      "  }),",
      "  handler: async (ctx, args) => {",
      "    const identity = await ctx.auth.getUserIdentity();",
      "    if (!identity) {",
      '      throw new Error("Authentication required.");',
      "    }",
      "    await ctx.runMutation(checkUploadLimit, { userId: identity.subject });",
      "",
      "    const requiredCode = process.env.WEDDING_UPLOAD_CODE;",
      "    if (requiredCode) {",
      "      const provided = args.uploadCode?.trim();",
      "      if (!provided || provided !== requiredCode) {",
      '        throw new Error("Upload code required.");',
      "      }",
      "    }",
      "",
      '    const notifyUrl = requireEnv("TRANSLOADIT_NOTIFY_URL");',
      "    const steps = buildWeddingSteps();",
      "    const fileCount = Math.max(1, args.fileCount);",
      "    return ctx.runAction(components.transloadit.lib.createAssembly, {",
      "      steps,",
      "      notifyUrl,",
      "      numExpectedUploadFiles: fileCount,",
      "      fields: {",
      '        guestName: args.guestName ?? "Guest",',
      '        album: "wedding-gallery",',
      "        fileCount,",
      "        userId: identity.subject,",
      "      },",
      "      userId: identity.subject,",
      "      config: {",
      '        authKey: requireEnv("TRANSLOADIT_KEY"),',
      '        authSecret: requireEnv("TRANSLOADIT_SECRET"),',
      "      },",
      "    });",
      "  },",
      "});",
      "",
    ].join("\n"),
    "utf8",
  );

  await writeFile(
    join(convexDir, "http.ts"),
    [
      'import { parseTransloaditWebhook } from "@transloadit/convex";',
      'import { httpRouter, httpActionGeneric } from "convex/server";',
      'import { queueWebhook } from "./transloadit";',
      "",
      "const http = httpRouter();",
      "const httpAction = httpActionGeneric;",
      "",
      "http.route({",
      '  path: "/transloadit/webhook",',
      '  method: "POST",',
      "  handler: httpAction(async (ctx, request) => {",
      "    const { payload, rawBody, signature } =",
      "      await parseTransloaditWebhook(request);",
      "",
      "    await ctx.runAction(queueWebhook, {",
      "      payload,",
      "      rawBody,",
      "      signature,",
      "    });",
      "",
      "    return new Response(null, { status: 202 });",
      "  }),",
      "});",
      "",
      "export default http;",
      "",
    ].join("\n"),
    "utf8",
  );
};
